# Generated by Django 4.2.7 on 2024-05-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='emoji',
            field=models.CharField(default='🍀', max_length=1),
            preserve_default=False,
        ),
    ]
