# Generated by Django 4.2.7 on 2024-06-02 20:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_eventmember_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('media', models.ImageField(blank=True, null=True, upload_to=event.models.upload_flashback_to)),
                ('event_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventmember')),
            ],
        ),
    ]
