# Generated by Django 5.0.7 on 2024-12-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_mutual_friends_limit_event_viewers_modes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='viewers_modes',
            new_name='viewers_mode',
        ),
    ]
