# Generated by Django 5.0.7 on 2024-12-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_viewers_modes_event_viewers_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventViewer',
        ),
    ]
