# Generated by Django 5.0.7 on 2024-12-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_delete_eventviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashback',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
