# Generated by Django 5.0.7 on 2024-12-26 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_eventviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventviewer',
            name='is_opened',
        ),
        migrations.CreateModel(
            name='FlashbackViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False)),
                ('event_viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventviewer')),
                ('flashback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.flashback')),
            ],
            options={
                'unique_together': {('event_viewer', 'flashback')},
            },
        ),
    ]
