# Generated by Django 5.0.7 on 2024-12-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_eventviewer_is_opened_flashbackviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('flashback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.flashback')),
            ],
            options={
                'unique_together': {('event', 'flashback')},
            },
        ),
    ]
