# Generated by Django 5.0.7 on 2024-12-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_eventpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpreview',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
