# Generated by Django 5.0.7 on 2024-12-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_eventpreview_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashback',
            name='seen',
        ),
        migrations.AddField(
            model_name='flashback',
            name='visibility',
            field=models.IntegerField(choices=[(0, 'public'), (1, 'private')], default=0),
        ),
    ]
