# Generated by Django 5.0.7 on 2025-01-09 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_flashback_seen_flashback_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='eventpreview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='eventpreview',
            constraint=models.UniqueConstraint(fields=('event', 'flashback'), name='unique_event_preview_event_flashback'),
        ),
        migrations.AddConstraint(
            model_name='eventpreview',
            constraint=models.UniqueConstraint(fields=('event', 'order'), name='unique_event_preview_event_order'),
        ),
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
