# Generated by Django 5.0.7 on 2025-01-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_message_alter_eventpreview_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
