# Generated by Django 5.0.7 on 2025-01-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventviewer',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
