# Generated by Django 5.0.7 on 2025-02-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_eventviewer_is_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_nsfw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashback',
            name='is_nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
