# Generated by Django 5.0.7 on 2025-02-04 16:07

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_alter_eventqrcode_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventqrcode',
            name='code',
            field=models.CharField(default=event.models.generate_event_qrcode_code, max_length=8),
        ),
    ]
