# Generated by Django 5.0.7 on 2025-02-05 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_eventqrcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventqrcode',
            name='image',
        ),
        migrations.CreateModel(
            name='EventPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='000000', max_length=6)),
                ('pdf_file', models.FileField(blank=True, upload_to='poster/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventpostertemplate')),
            ],
            options={
                'unique_together': {('event', 'template')},
            },
        ),
    ]
