# Generated by Django 5.0.7 on 2025-02-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_remove_eventqrcode_image_eventposter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventposter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventposter',
            name='light_color',
            field=models.CharField(default='ffffff', max_length=8),
        ),
        migrations.AlterField(
            model_name='eventposter',
            name='color',
            field=models.CharField(default='ffffff', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='eventposter',
            unique_together={('event', 'template', 'color')},
        ),
    ]
