# Generated by Django 5.0.7 on 2025-02-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_alter_eventposter_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPoster',
        ),
    ]
