# Generated by Django 5.0.7 on 2025-02-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_delete_eventposter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPosterTemplateColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=8, unique=True)),
                ('light_color', models.CharField(default='ffffff', max_length=8)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_palettes', to='event.eventpostertemplate')),
            ],
        ),
    ]
