# Generated by Django 5.0.7 on 2025-02-09 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_eventpostertemplatecolorpalette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpostertemplatecolorpalette',
            name='color',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a valid hex color code (e.g., #FFFFFF or #FFFFFFFF).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$')]),
        ),
        migrations.AlterField(
            model_name='eventpostertemplatecolorpalette',
            name='light_color',
            field=models.CharField(default='#ffffff', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a valid hex color code (e.g., #FFFFFF or #FFFFFFFF).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$')]),
        ),
    ]
