# Generated by Django 5.0.7 on 2025-02-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0028_alter_eventpostertemplatecolorpalette_color_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventQrCode',
            new_name='EventInviteCode',
        ),
    ]
