# Generated by Django 5.0.7 on 2025-02-09 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_rename_eventqrcode_eventinvitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpostertemplatecolorpalette',
            name='color',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_hex_color', message='Enter a valid hex color code (e.g., #FFFFFF or #FFFFFFFF).', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$')]),
        ),
        migrations.AlterUniqueTogether(
            name='eventpostertemplatecolorpalette',
            unique_together={('template', 'color')},
        ),
    ]
