# Generated by Django 5.0.7 on 2025-02-15 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_eventmember_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvite',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
