# Generated by Django 5.0.7 on 2025-02-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_eventinvite_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventpreview',
            name='unique_event_preview_event_flashback',
        ),
    ]
