# Generated by Django 5.0.7 on 2025-02-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_remove_eventpreview_unique_event_preview_event_flashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_close_actions',
            field=models.BooleanField(default=False),
        ),
    ]
