# Generated by Django 5.0.7 on 2025-03-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_event_post_close_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashback',
            name='media_type',
            field=models.IntegerField(choices=[(0, 'photo'), (1, 'video')], default=0),
        ),
    ]
