# Generated by Django 5.0.7 on 2025-03-07 15:09

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_flashback_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashback',
            name='video_media',
            field=models.FileField(blank=True, default=None, null=True, upload_to=event.models.upload_flashback_to),
        ),
        migrations.AlterField(
            model_name='flashback',
            name='media',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=event.models.upload_flashback_to),
        ),
    ]
