# Generated by Django 5.0.7 on 2025-03-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_flashback_video_media_alter_flashback_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashback',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
