# Generated by Django 5.0.7 on 2025-03-12 19:58

import backend.storage_backends
import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0037_flashback_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashback',
            name='media',
            field=models.ImageField(blank=True, default=None, null=True, storage=backend.storage_backends.PrivateMediaStorage(), upload_to=event.models.upload_flashback_to),
        ),
        migrations.AlterField(
            model_name='flashback',
            name='video_media',
            field=models.FileField(blank=True, default=None, null=True, storage=backend.storage_backends.PrivateMediaStorage(), upload_to=event.models.upload_flashback_to),
        ),
    ]
