# Generated by Django 5.0.7 on 2025-03-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0038_alter_flashback_media_alter_flashback_video_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashback',
            name='is_nsfw',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
