# Generated by Django 5.0.7 on 2025-03-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_alter_flashback_is_nsfw'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashbackVideoCheckNsfwJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.flashback')),
            ],
        ),
    ]
