# Generated by Django 5.0.7 on 2025-03-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_flashbackvideochecknsfwjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashbackvideochecknsfwjob',
            name='flashback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nsfw_job', to='event.flashback'),
        ),
    ]
