# Generated by Django 4.1.7 on 2024-01-05 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
