# Generated by Django 4.1.7 on 2024-01-05 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_friendrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
