# Generated by Django 4.2.7 on 2024-01-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
