# Generated by Django 5.0.7 on 2025-01-31 11:52

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=user.models.default_profile_picture, upload_to=user.models.upload_profile_to),
        ),
    ]
