# Generated by Django 5.0.7 on 2025-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
